package downloaddemo.liyanying.example.com.download.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import downloaddemo.liyanying.example.com.download.dao.DownLoadInfo;

import downloaddemo.liyanying.example.com.download.greendao.DownLoadInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downLoadInfoDaoConfig;

    private final DownLoadInfoDao downLoadInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downLoadInfoDaoConfig = daoConfigMap.get(DownLoadInfoDao.class).clone();
        downLoadInfoDaoConfig.initIdentityScope(type);

        downLoadInfoDao = new DownLoadInfoDao(downLoadInfoDaoConfig, this);

        registerDao(DownLoadInfo.class, downLoadInfoDao);
    }
    
    public void clear() {
        downLoadInfoDaoConfig.clearIdentityScope();
    }

    public DownLoadInfoDao getDownLoadInfoDao() {
        return downLoadInfoDao;
    }

}
